EOS-12944-cortx-dev: Add support for JBOD health view
Seagate/cortx-manager pull request #144
Opened 2020-09-30 18:31 UTC by pawankumarsrivastava

2020-10-03 04:00 UTC, prathameshrodi requested changes

2020-10-03 04:00 UTC, prathameshrodi commented on csm/core/services/health.py
> +                if isinstance(value, dict):
Change this to 
```
if not isinstance(value, dict):
    continue
```
Writing big if statements as per python.

2020-10-06 06:59 UTC, prathameshrodi approved these changes

2020-10-13 06:43 UTC, pawankumarsrivastava commented
Not required for cortx1.0-dev. Closing this one

2020-10-13 06:43 UTC, closed without merging