Create s3 accounts script
Seagate/cortx-manager pull request #214
Opened 2020-10-19 17:16 UTC by soniyamoholkar

# Backend

## Problem Statement
<pre>
Story Ref (if any):
</pre>
## Unit testing on RPM done
<pre>
No
</pre>
## Problem Description: Script required to create s3 acounts, IAM users, buckets
<pre>

</pre>
## Solution: Python script created
<pre>

</pre>
## Unit Test Cases - Tested on local VM
<pre>

</pre>
Signed-off-by: Soniya Moholkar

2020-10-20 06:11 UTC, ajaysrivas requested changes

2020-10-20 06:11 UTC, ajaysrivas commented on csm/conf/create_accounts.py
> +class CreateAccount:
Use a noun for class name.

2020-10-20 06:11 UTC, ajaysrivas commented on csm/conf/create_accounts.py
> +import requests
Move this file to test folder.

2020-10-22 13:38 UTC, soniyamoholkar commented on csm/conf/create_accounts.py
> +class CreateAccount:
Done.

2020-10-22 13:38 UTC, soniyamoholkar commented on csm/conf/create_accounts.py
> +import requests
moved file to /test/s3

2020-12-02 06:42 UTC, kupranay commented
We dont require this code in cortx 1.0 branch hence closing it. @soniyamoholkar  if not already raised please raise it for main with above comments fixed

2020-12-02 06:42 UTC, closed without merging