EOS-20329: CLI Framework movement
Seagate/cortx-manager pull request #463
Opened 2021-05-10 14:43 UTC by udayan-y21

Signed-off-by: Udayan Yaragattikar <udayan.yaragattikar@seagate.com>

# Backend

## Problem Statement
<pre>
Story Ref (if any):  https://jts.seagate.com/browse/EOS-20329
</pre>
## Unit testing on RPM done
<pre>
Yes
</pre>
Custom-Ci Build : [Custom-CI#1297](http://cortx-storage.colo.seagate.com/releases/cortx/github/integration-custom-ci/centos-7.8.2003/custom-build-1297/)
Deployment Job: http://eos-jenkins.colo.seagate.com/job/Cortx-Deployment/job/VM-Deployment-R2-1Node/681/console

## Problem Description
<pre>
CLI framework was bound to CSM, required to be moved to foundation repo, so that it can be consumed by other components to build there own CLI
</pre>
## Solution
<pre>
CLI framework moved to foundation repo. Changes in CSM repo inscludes minor modifications of hardcoaded part and other testing modifications
</pre>
PR linnk for Py-utils repo: https://github.com/Seagate/cortx-utils/pull/279
## Unit Test Cases
## CSM operations
<pre>
User Creation and Show
</pre>
![image](https://user-images.githubusercontent.com/66424882/117953574-c5e8bb80-b333-11eb-8332-bc86f73cde37.png)
<pre>
Alerts show
</pre>
![image](https://user-images.githubusercontent.com/66424882/117953838-0ea07480-b334-11eb-8d45-195a44761c25.png)
<pre>
Security details
</pre>
![image](https://user-images.githubusercontent.com/66424882/117954053-46a7b780-b334-11eb-95e2-c9c228205764.png)
## Supportbundle
<pre>
Support bundle
</pre>
![image](https://user-images.githubusercontent.com/66424882/117954817-06950480-b335-11eb-84fb-7050ad82fbc4.png)

## S3 operations
<pre>
s3 account show
</pre>
![image](https://user-images.githubusercontent.com/66424882/117955805-0cd7b080-b336-11eb-8638-7f43ae848b96.png)

<pre>
s3bucket create and show
</pre>
![image](https://user-images.githubusercontent.com/66424882/117955982-3a245e80-b336-11eb-8c50-6c0b0bcfc843.png)
<pre>
s3 iam user create and show
</pre>
![image](https://user-images.githubusercontent.com/66424882/117956240-7e176380-b336-11eb-9d96-c729b6a05989.png)

## CSM_SETUP
![image](https://user-images.githubusercontent.com/66424882/117957444-b5d2db00-b337-11eb-9cff-c7ec289a2219.png)

Signed-off-by:

2021-05-16 13:38 UTC, pawankumarsrivastava requested changes

2021-05-16 13:38 UTC, pawankumarsrivastava commented on csm/cli/cli_validators.py
> +# CORTX-CSM: CORTX Management web and CLI interface.
The CLI validators class will be required for other components too. You can have a base class in py-utils having commons validations and extend that class in CSM for CSM specific validations.

2021-05-17 18:19 UTC, pawankumarsrivastava approved these changes

2021-05-18 09:09 UTC, soniyamoholkar approved these changes

2021-06-09 06:32 UTC, kupranay approved these changes

2021-06-10 06:32 UTC, merged