EOS-20373:Implementation for limit to create CORTX administrative accounts
Seagate/cortx-manager pull request #510
Opened 2021-06-10 10:35 UTC by rohitkolapkar

# Backend

## Problem Statement
<pre>
Story Ref (if any):
</pre>
[EOS-20373](https://jts.seagate.com/browse/EOS-20373)
## Unit testing on RPM done
<pre>
Yes
</pre>
## Problem Description

- Limit to create CORTX administrative accounts for LR2
- Max users allowed = 100

## Solution
- Added new key in csm.conf to configure the value of max users allowed.
- Logic implemented to restrict account creation if maximum users limit reached.
## Unit Test Cases
- Account creation fails if maximum users limit reached.

1. On GUI
![image](https://user-images.githubusercontent.com/36843912/120976549-10712280-c790-11eb-9b72-1ff414ec16b8.png)

2. On Cortxcli
![image](https://user-images.githubusercontent.com/36843912/120999552-e119e000-c7a6-11eb-9737-cf6f7ca0b9f9.png)

3. Postman
![image](https://user-images.githubusercontent.com/36843912/121004509-66ec5a00-c7ac-11eb-9082-5c7e94758c40.png)

Signed-off-by: rohitkolapkar <rohit.j.kolapkar@seagate.com>

2021-06-10 13:38 UTC, avrnv requested changes

2021-06-10 13:38 UTC, avrnv commented on csm/conf/etc/csm/csm.conf
> +    max_users_allowed: 100
Minor: please, end the new line to the end of the file.

2021-06-10 13:38 UTC, avrnv commented on csm/core/controllers/users.py
> +        max_users_allowed = Conf.get(const.CSM_GLOBAL_INDEX, f"{const.CSM_MAX_USERS_ALLOWED}")
Why do you need f-string as the second parameter to Conf.get?

2021-06-10 13:38 UTC, avrnv commented on csm/core/services/users.py
> +        returns the count of existing users
Minor: start the comment with a capital letter. PEP also suggests 'Return' instead of 'Returns'.

2021-06-10 13:53 UTC, udayan-y21 approved these changes

2021-06-11 07:14 UTC, avrnv approved these changes

2021-06-15 06:13 UTC, kupranay approved these changes

2021-06-15 06:13 UTC, merged