Pre-factory modificaions  in cleanup command
Seagate/cortx-manager pull request #598
Opened 2021-08-02 06:05 UTC by udayan-y21

Signed-off-by: Udayan Yaragattikar <udayan.yaragattikar@seagate.com>

# Backend

# Problem Statement

- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_
- _Describe the problem this patch intends to solve._

## Design

- _For Bug describe the fix here._
- _For feature, post the link to the solution page._
- _Any northbound interface change and has been notified to other gatekeepers [Y/N]:_

## Coding

- _Coding conventions are followed and code is consistent. Yes/No?_
- _Confirm All CODACY errors are resolved. Yes/No?_

## Testing

- _Confirm that Test Cases are added (for both the cases, fix and feature). Yes/No?_
- _Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability. Yes/No?_
- _Confirm Testing was performed with installed RPM. Yes/No?_
- _Confirm all the ut/regression/smoke test has been performed [Y/N]_

## Checklist

- _PR is self-reviewed? Yes/No?_
- _GitHub Issue is updated_
- _Jira is updated_
  -  _Check if the description is clear and explained._ 
    -  _Check Acceptance Criterion is defined._
      -  _All the tests performed should be mentioned before Resolving a JIRA._
        -  _Verification needs to be done before marked as Closed/Verified_
        - _Any interface change Yes/No?_
        - _Change notified to other gatekeepers: Yes/No?_
        - _Code reviews done and addressed: Yes/No?_
        - _Codacy issues reviewed and addressed: Yes/No?_
        - _Deployment test : Done/Not?_
        - _UT/smoke test: Done/Not?_
        - _Jira number added to PR: Yes/No?_
        - _Github merge done using UI: Yes/No?_
        - _Side effects on other features - deployment/update/node-replacement_
        - _Changes to quick-start-guide/community impact_
        - _All dependent component code PR are raised or already merged Yes/No_
        - _All dependent code already merged in landing branch Yes/No_

2021-08-04 09:53 UTC, pawankumarsrivastava requested changes
Minor changes

2021-08-04 09:53 UTC, pawankumarsrivastava commented on csm/conf/cleanup.py
> +        Log.info(f"Replace service file.")
Replace -> Replacing

2021-08-04 09:53 UTC, pawankumarsrivastava commented on csm/conf/cleanup.py
> +            #               pre-factory (Postinstall) stage
Indentation for comment

2021-08-04 09:53 UTC, pawankumarsrivastava commented on csm/conf/cleanup.py
> +            Log.info(f"Remove Service user: {self._user}")
Remove -> Removing

2021-08-04 16:38 UTC, udayan-y21 commented on csm/conf/cleanup.py
> +        Log.info(f"Replace service file.")
Modifications done

2021-08-04 16:39 UTC, udayan-y21 commented on csm/conf/cleanup.py
> +            #               pre-factory (Postinstall) stage
Modifications done

2021-08-04 16:39 UTC, udayan-y21 commented on csm/conf/cleanup.py
> +            Log.info(f"Remove Service user: {self._user}")
Modifications done

2021-08-09 12:20 UTC, soniyamoholkar approved these changes

2021-08-10 08:42 UTC, pawankumarsrivastava approved these changes

2021-08-10 08:42 UTC, merged