EOS-24242: Reset password is shown in audit logs
Seagate/cortx-manager pull request #662
Opened 2021-09-30 12:58 UTC by soniyamoholkar

Signed-off-by: Soniya Moholkar <soniya.moholkar@seagate.com>

# Backend

# Problem Statement

- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_ EOS-24242
- _Describe the problem this patch intends to solve._
- Reset password is displayed in CSM audit logs.

## Design

- Check if password is present in request param/payload.
- If yes, remove the field while logging.

## Coding

- _Coding conventions are followed and code is consistent. Yes/No?_ Yes
- _Confirm All CODACY errors are resolved. Yes/No?_ Yes

## Testing

- _Confirm that Test Cases are added (for both the cases, fix and feature). Yes/No?_
- _Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability. Yes/No?_
- _Confirm Testing was performed with installed RPM. Yes/No?_ Yes
- _Confirm all the ut/regression/smoke test has been performed [Y/N]_

## Checklist

- _PR is self-reviewed? Yes/No?_ Yes
- _GitHub Issue is updated_
- _Jira is updated_
  -  _Check if the description is clear and explained._ 
    -  _Check Acceptance Criterion is defined._
      -  _All the tests performed should be mentioned before Resolving a JIRA._
        -  _Verification needs to be done before marked as Closed/Verified_
        - _Any interface change Yes/No?_
        - _Change notified to other gatekeepers: Yes/No?_
        - _Code reviews done and addressed: Yes/No?_
        - _Codacy issues reviewed and addressed: Yes/No?_
        - _Deployment test : Done/Not?_
        - _UT/smoke test: Done/Not?_
        - _Jira number added to PR: Yes/No?_
        - _Github merge done using UI: Yes/No?_
        - _Side effects on other features - deployment/update/node-replacement_
        - _Changes to quick-start-guide/community impact_
        - _All dependent component code PR are raised or already merged Yes/No_
        - _All dependent code already merged in landing branch Yes/No_

2021-10-01 04:24 UTC, pawankumarsrivastava requested changes

2021-10-01 04:24 UTC, pawankumarsrivastava commented on csm/core/agent/api.py
> +                        if key.lower().find("password".lower()) > -1 or \
is 2 times lower required here?

2021-10-04 06:18 UTC, soniyamoholkar commented on csm/core/agent/api.py
> +                        if key.lower().find("password".lower()) > -1 or \
Addressed. Please check

2021-10-04 09:38 UTC, pawankumarsrivastava approved these changes

2021-10-04 09:39 UTC, shrimetta approved these changes

2021-10-04 09:46 UTC, udayan-y21 approved these changes

2021-10-04 11:41 UTC, kupranay approved these changes

2021-10-04 11:41 UTC, merged