Controller view and hardcoded response in service added
Seagate/cortx-manager pull request #808
Opened 2022-04-19 13:56 UTC by abhijit1patil

Signed-off-by: abhijit1patil <abhijit.1.patil@seagate.com>

# Problem Statement
- [CORTX-30285 JIRA Ticket](https://jts.seagate.com/browse/CORTX-30285)

# Design
-  [REST API Specification](https://seagate-systems.atlassian.net/l/c/ms1J10fi)

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

2022-04-28 04:59 UTC, pawankumarsrivastava requested changes

2022-04-28 04:59 UTC, pawankumarsrivastava commented on csm/core/controllers/storage_capacity.py
> +@CsmView._app_routes.view("/api/v2/capacity/{resource}/{id}")
/api/v2/capacity/{resource}/{id} -> /api/v2/capacity/s3/{resource}/{id}

2022-04-28 09:12 UTC, abhijit1patil commented on csm/core/controllers/storage_capacity.py
> +@CsmView._app_routes.view("/api/v2/capacity/{resource}/{id}")
updated

2022-05-02 05:01 UTC, pawankumarsrivastava approved these changes

2022-05-02 05:01 UTC, merged