CORTX-30315: Get Node status
Seagate/cortx-manager pull request #813
Opened 2022-04-26 08:45 UTC by abhijit1patil

# Problem Statement
- [CORTX-30315 JIRA Ticket](https://jts.seagate.com/browse/CORTX-30315)

# Design
-  Supported Confluence Specification:-
[HA REST APIs - Private-Cortx - Confluence (atlassian.net)](https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/981434369/HA+REST+APIs)

[Node failure API specifications - Private-Cortx - Confluence (atlassian.net)](https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/983400463/Node+failure+API+specifications)

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

2022-04-28 04:34 UTC, pawankumarsrivastava commented on csm/conf/configure.py
> +        # self.set_ha_endpoint()
Add TODO here

2022-04-28 04:53 UTC, pawankumarsrivastava requested changes

2022-04-28 04:53 UTC, pawankumarsrivastava commented on csm/conf/configure.py
> +        # self.set_ha_endpoint()
Add TODO here with details

2022-04-28 04:53 UTC, pawankumarsrivastava commented on csm/conf/configure.py
> +        for endpoint in endpoints:
There will only be 1 endpoint. No need of a for loop

2022-04-28 04:53 UTC, pawankumarsrivastava commented on csm/conf/configure.py
> +        for endpoint in endpoints:
No need of _get_ha_endpoint

2022-04-28 04:53 UTC, pawankumarsrivastava commented on csm/conf/csm_default.conf
> +    resource_status_api: /v1/system/health/
Remove this key and add it to schema file

2022-04-28 04:53 UTC, pawankumarsrivastava commented on csm/conf/etc/csm/csm.conf
> +    resource_status_api: "/v1/system/health/"
same here

2022-04-28 04:53 UTC, pawankumarsrivastava commented on csm/core/blogic/const.py
> +CLUSTER_MANAGMENT_HA_CLUSTER_API ='CLUSTER_MANAGEMENT>cluster_status_api'
Remove it

2022-04-28 04:53 UTC, pawankumarsrivastava commented on csm/core/controllers/cluster_management.py
> +@CsmView._app_routes.view("/api/v2/system/management/{resource}/{id}")
Change the endpoint as per doc

2022-04-28 04:53 UTC, pawankumarsrivastava commented on csm/core/controllers/cluster_management.py
> +        API to get cluster resource status with id
API to get cluster resource status with id --> This will get the health of a resource in the system

2022-04-28 04:53 UTC, pawankumarsrivastava commented on csm/core/controllers/cluster_management.py
> +        Log.debug(f" Get status for {resource} with id: {resource_id}")
Getting the status

2022-04-28 04:53 UTC, pawankumarsrivastava commented on csm/core/services/cluster_management.py
> +        Log.debug(f"ClusterOperationsAppService: Making plugin call with arguments: "
GetResourceStatus: Args : { }

2022-04-28 04:53 UTC, pawankumarsrivastava commented on csm/plugins/cortx/cluster_management.py
> +import aiohttp
Removed unused imports

2022-04-28 04:53 UTC, pawankumarsrivastava commented on csm/plugins/cortx/cluster_management.py
> +        id = kwargs.get(const.ARG_RESOURCE_ID, "")
Return success. Remove all the logic

2022-04-28 06:18 UTC, abhijit1patil commented on csm/conf/configure.py
> +        # self.set_ha_endpoint()
updated

2022-05-02 05:00 UTC, pawankumarsrivastava approved these changes

2022-05-02 05:00 UTC, merged