CORTX-31170: CSM user management and IAM users management API changes
Seagate/cortx-manager pull request #822
Opened 2022-05-11 07:14 UTC by abhijit1patil

Signed-off-by: abhijit1patil <abhijit.1.patil@seagate.com>

# Problem Statement
- [CORTX-31170 JIRA ticket](https://jts.seagate.com/browse/CORTX-31170)

# Design
-  [Management API Changes](https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/1006305559/Management+API+Changes)

# Coding
   Checklist for Author
-  [ ] Coding conventions are followed and code is consistent

# Testing 
  Checklist for Author
- [ ] Unit and System Tests are added
- [ ] Test Cases cover Happy Path, Non-Happy Path and Scalability
- [ ] Testing was performed with RPM

# Impact Analysis
  Checklist for Author/Reviewer/GateKeeper
- [ ] Interface change (if any) are documented
- [ ] Side effects on other features (deployment/upgrade)
- [ ] Dependencies on other component(s)

# Review Checklist 
  Checklist for Author
- [ ] JIRA number/GitHub Issue added to PR
- [ ] PR is self reviewed
- [ ] Jira and state/status is updated and JIRA is updated with PR link
- [ ] Check if the description is clear and explained

# Documentation
  Checklist for Author
- [ ] Changes done to WIKI / Confluence page / Quick Start Guide

2022-05-16 05:01 UTC, pawankumarsrivastava requested changes

2022-05-16 05:01 UTC, pawankumarsrivastava commented on csm/core/controllers/users.py
> +@CsmView._app_routes.view("/api/v2/users")
Change /api/v2/users -> /api/v2/system/users

2022-05-16 05:01 UTC, pawankumarsrivastava commented on csm/core/controllers/users.py
> +@CsmView._app_routes.view("/api/v2/users")
Change /api/v2/users -> /api/v2/system/users

2022-05-16 05:01 UTC, pawankumarsrivastava commented on csm/core/controllers/users.py
> +@CsmView._app_routes.view("/api/v2/users/{user_id}")
Change /api/v2/users/{user_id} -> /api/v2/system/users/{user_id}

2022-05-16 05:01 UTC, pawankumarsrivastava commented on csm/core/controllers/users.py
> +@CsmView._app_routes.view("/api/v2/users/{user_id}")
Change /api/v2/users/{user_id} -> /api/v2/system/users/{user_id}

2022-05-16 05:01 UTC, pawankumarsrivastava commented on csm/core/controllers/users.py
> +@CsmView._app_routes.view("/api/v1/users")
Please do not change any v1 api's

2022-05-16 05:01 UTC, pawankumarsrivastava commented on csm/core/controllers/users.py
> +@CsmView._app_routes.view("/api/v1/users")
Please do not change any v1 api's

2022-05-16 05:44 UTC, abhijit1patil commented on csm/core/controllers/users.py
> +@CsmView._app_routes.view("/api/v2/users")
updated

2022-05-16 05:44 UTC, abhijit1patil commented on csm/core/controllers/users.py
> +@CsmView._app_routes.view("/api/v2/users")
updated

2022-05-16 05:44 UTC, abhijit1patil commented on csm/core/controllers/users.py
> +@CsmView._app_routes.view("/api/v2/users/{user_id}")
updated

2022-05-16 05:44 UTC, abhijit1patil commented on csm/core/controllers/users.py
> +@CsmView._app_routes.view("/api/v2/users/{user_id}")
updated

2022-05-16 05:44 UTC, abhijit1patil commented on csm/core/controllers/users.py
> +@CsmView._app_routes.view("/api/v1/users")
updated

2022-05-16 05:45 UTC, abhijit1patil commented on csm/core/controllers/users.py
> +@CsmView._app_routes.view("/api/v1/users")
updated

2022-05-17 08:54 UTC, rohitkolapkar approved these changes

2022-05-17 10:49 UTC, merged