CORTX-31824: Expose CSM APIs for Activity Tracker
Seagate/cortx-manager pull request #859
Opened 2022-06-13 03:58 UTC by rohitkolapkar

Signed-off-by: Rohit Kolapkar <rohit.j.kolapkar@seagate.com>

# Pull Request
## Problem Statement
-   Problem statement

## Design
-   For Bug, Describe the fix here.
-   For Feature, Post the link for design

## Coding
>   Checklist for Author
-   \[ \] Coding conventions are followed and code is consistent

## Testing 
>   Checklist for Author
-   \[ \] Unit and System Tests are added
-   \[ \] Test Cases cover Happy Path, Non-Happy Path and Scalability
-   \[ \] Testing was performed with RPM

## Impact Analysis
>   Checklist for Author/Reviewer/GateKeeper
-   \[ \] Interface change (if any) are documented
-   \[ \] Side effects on other features (deployment/upgrade)
-   \[ \] Dependencies on other component(s)

## Review Checklist 
>   Checklist for Author
-   \[ \] JIRA number/GitHub Issue added to PR
-   \[ \] PR is self reviewed
-   \[ \] Jira and state/status is updated and JIRA is updated with PR link
-   \[ \] Check if the description is clear and explained

## Documentation
>   Checklist for Author
-   \[ \] Changes done to WIKI / Confluence page / Quick Start Guide

2022-06-14 06:57 UTC, rohitkolapkar commented
@pawankumarsrivastava  @kupranay This PR is dependent on Utils PR - https://github.com/Seagate/cortx-utils/pull/834

2022-06-14 07:03 UTC, abhijit1patil requested changes

2022-06-14 07:03 UTC, abhijit1patil commented on csm/core/controllers/activities.py
> +            raise InvalidRequest("Could not parse request body, invalid JSON received.")
you can use const.JSON_ERROR

2022-06-14 07:08 UTC, rohitkolapkar commented on csm/core/controllers/activities.py
> +            raise InvalidRequest("Could not parse request body, invalid JSON received.")
yes, thanks for reminding.

2022-06-14 07:08 UTC, rohitkolapkar commented on csm/core/controllers/activities.py
> +            raise InvalidRequest("Could not parse request body, invalid JSON received.")
updated.

2022-06-14 07:08 UTC, rohitkolapkar commented on csm/core/controllers/activities.py
> +            raise InvalidRequest("Could not parse request body, invalid JSON received.")
updated.

2022-06-14 08:34 UTC, rohitkolapkar commented
1N Deployment is failing because of dependency over Utils PR.
Custom Ci - passed
https://eos-jenkins.colo.seagate.com/job/GitHub-custom-ci-builds/job/generic/job/custom-ci/6688/console

2022-06-14 09:52 UTC, pawankumarsrivastava requested changes

2022-06-14 09:52 UTC, pawankumarsrivastava commented on csm/core/controllers/activities.py
> +@CsmView._app_routes.view("/api/v2/activities")
/api/v2/activities or /api/v2/activity ?

2022-06-14 10:08 UTC, rohitkolapkar commented on csm/core/controllers/activities.py
> +@CsmView._app_routes.view("/api/v2/activities")
as per REST API norms - /api/v2/activities

2022-06-15 06:58 UTC, pawankumarsrivastava approved these changes

2022-06-23 15:01 UTC, abhijit1patil requested changes

2022-06-23 18:04 UTC, rohitkolapkar commented on csm/core/controllers/activities.py
> +    pct_progress = fields.Int(data_key=const.PCT_PROGRESS)
This is the base schema, there are more schemas based  on status value.
FYI, required=true covers allow_none=False and missing=None is not required here. 
Also please go through API specs for update api.

2022-06-23 18:04 UTC, rohitkolapkar commented on csm/core/services/activities.py
> +# CORTX-CSM: CORTX Management web and CLI interface.
removed

2022-06-24 05:14 UTC, abhijit1patil approved these changes

2022-06-27 03:24 UTC, pawankumarsrivastava requested changes
Please update the following - 
1. Swagger Doc
2. CSM Endpoints Doc - https://seagate-systems.atlassian.net/wiki/spaces/PUB/pages/994836509/CORTX+Management+Endpoints

2022-06-27 19:47 UTC, pawankumarsrivastava approved these changes

2022-06-27 19:47 UTC, merged