Cortx30048 CSM Logs
Seagate/cortx-manager pull request #895
Opened 2022-08-23 14:07 UTC by ShivamVerma380

# Pull Request
## Problem Statement
-   Problem statement

## Design
-   For Bug, Describe the fix here.
-   For Feature, Post the link for design

## Coding
>   Checklist for Author
-   \[ \] Coding conventions are followed and code is consistent

## Testing 
>   Checklist for Author
-   \[ \] Unit and System Tests are added
-   \[ \] Test Cases cover Happy Path, Non-Happy Path and Scalability
-   \[ \] Testing was performed with RPM

## Impact Analysis
>   Checklist for Author/Reviewer/GateKeeper
-   \[ \] Interface change (if any) are documented
-   \[ \] Side effects on other features (deployment/upgrade)
-   \[ \] Dependencies on other component(s)

## Review Checklist 
>   Checklist for Author
-   \[ \] JIRA number/GitHub Issue added to PR
-   \[ \] PR is self reviewed
-   \[ \] Jira and state/status is updated and JIRA is updated with PR link
-   \[ \] Check if the description is clear and explained

## Documentation
>   Checklist for Author
-   \[ \] Changes done to WIKI / Confluence page / Quick Start Guide

2022-08-23 14:17 UTC, cortx-admin commented
Can one of the admins verify this patch?

2022-08-25 05:18 UTC, rohitkolapkar requested changes

2022-08-25 05:18 UTC, rohitkolapkar commented on csm/core/controllers/storage_capacity.py
> +
please fix this duplication.

2022-08-25 05:18 UTC, rohitkolapkar commented on csm/core/agent/api.py
> +        return True
Add new line at the end of the file

2022-08-25 05:18 UTC, rohitkolapkar commented on csm/core/controllers/login.py
> +        return CsmResponse()
Add new line at the end of the file

2022-08-25 05:18 UTC, rohitkolapkar commented on csm/core/controllers/rgw/s3/users.py
> +            return CsmResponse(response)
Add new line at the end of the file

2022-08-25 05:18 UTC, rohitkolapkar commented on csm/core/controllers/users.py
> +        return resp
Add new line at the end of the file

2022-08-25 05:18 UTC, rohitkolapkar commented on csm/core/services/sessions.py
> +        return None
Add new line at the end of the file

2022-08-25 05:18 UTC, rohitkolapkar commented on csm/core/services/storage_capacity.py
> +        return plugin_response
Add new line at the end of the file

2022-08-29 08:35 UTC, ShivamVerma380 commented on csm/core/controllers/storage_capacity.py
> +
Fixed.

2022-08-29 08:35 UTC, ShivamVerma380 commented on csm/core/agent/api.py
> +        return True
Added new line at end of file

2022-08-29 08:36 UTC, ShivamVerma380 commented on csm/core/controllers/login.py
> +        return CsmResponse()
Added new line at end of file

2022-08-29 08:37 UTC, ShivamVerma380 commented on csm/core/controllers/rgw/s3/users.py
> +            return CsmResponse(response)
Added new line at end of file

2022-08-29 08:38 UTC, ShivamVerma380 commented on csm/core/controllers/users.py
> +        return resp
Added new line at end of file

2022-08-29 08:39 UTC, ShivamVerma380 commented on csm/core/services/sessions.py
> +        return None
Added new line at the end of file

2022-08-29 08:39 UTC, ShivamVerma380 commented on csm/core/services/storage_capacity.py
> +        return plugin_response
Added new line at end of file

2022-08-30 04:12 UTC, pawankumarsrivastava approved these changes

2022-08-30 04:43 UTC, rohitkolapkar approved these changes

2022-08-30 11:21 UTC, merged